### ISSUE TITLE
GET https://api.github.com/repos/fluxcd/flux2/releases/latest: 403 API rate limit exceeded 

### ISSUE THREAD

**Issue by gesslein** [23technologies/gardener-extension-shoot-flux#6]
**How to categorize this issue?**

/area scalability
/kind bug

**What happened**:
On a "random" shoot, the extension produced this error

`task "Waiting until extension resources are ready" failed: Error while waiting for Extension shoot--23ke-ci--23ke-run-d0ea/shoot-flux to become ready: error during reconciliation: Error reconciling extension: GET https://api.github.com/repos/fluxcd/flux2/releases/latest: 403 API rate limit exceeded for 168.119.x.x. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.) [rate reset in 15m38s]`

I just found that noteworthy but maybe you already hit something like that during development. Not sure if there is any room to hit the github api less frequently, but even then I believe it is unavoidable that a large enough deployment (especially behind f.e. a common NAT IP) would be hitting that rate limit at some point.

My gut instinct is that using "latest" is not a good idea due to breaking flux changes and non-declarative anyway and maybe selecting a flux version should just be mandatory.

**Comment by JensAc** [comment]
Sure, but there is no need to use `latest`. We could simply specify the flux version in the configuration `ConfigMap`. Would that resolve the issue?

**Comment by berendt** [comment]
Should we also mirror that and provide it directly to avoid rate limits? Regardless of latest or not latest.

**Comment by gesslein** [comment]
I see this in the context that our number of shoots using this extension is not that large and each node of the seed even has it's own external IP. But maybe the prediction from looking at the code would be that this API is hit very very infrequently anyway (on each controller start or only once per hour, no idea) and it couldn't have been this extensions own fault. That is maybe the first real question, are rate limits kept in mind in the code and "respected" already? Is using "latest" something that should work for reasonable large setups?

We could "resolve" the issue by not selecting latest in _our_ configuration of course, but then it's just waiting for the next person to hit that problem. I believe that "latest" has/will cause even more problems so in my opinion a discussion worthwhile to have first. Of course it is also a nice convenience and keeping software up to date "manually" is a constant challenge.
